In [9]:
import tensorflow as tf

### Define

In [10]:
a = tf.Variable(initial_value=[[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [11]:
b = tf.Variable(initial_value=[[-1, 2, -3], [4, -5, 6], [7, -8, -9]])
b

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[-1,  2, -3],
       [ 4, -5,  6],
       [ 7, -8, -9]], dtype=int32)>

### Operations

In [12]:
a ** 2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [16]:
a * 2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)>

In [17]:
a + 10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]], dtype=int32)>

In [18]:
a + b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0,  4,  0],
       [ 8,  0, 12],
       [14,  0,  0]], dtype=int32)>

In [20]:
a @ b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 28, -32, -18],
       [ 58, -65, -36],
       [ 88, -98, -54]], dtype=int32)>

In [21]:
tf.matmul(a, b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 28, -32, -18],
       [ 58, -65, -36],
       [ 88, -98, -54]], dtype=int32)>

In [24]:
tf.concat((a, b), axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1,  2, -3],
       [ 4, -5,  6],
       [ 7, -8, -9]], dtype=int32)>

In [25]:
tf.concat((a, b), axis=1)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 1,  2,  3, -1,  2, -3],
       [ 4,  5,  6,  4, -5,  6],
       [ 7,  8,  9,  7, -8, -9]], dtype=int32)>

end