In [2]:
import tensorflow as tf

## Gradient of Rank 0 (Calculus)

### First Order Derivative

In [3]:
input_var = tf.Variable(initial_value=3.0)
input_var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [8]:
with tf.GradientTape() as tape:
    result = tf.square(input_var) # x^2 (x=3) , dx = 2*x (2x = 6)
gradient = tape.gradient(result, input_var)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [9]:
pi = tf.constant(3.14)
pi

<tf.Tensor: shape=(), dtype=float32, numpy=3.140000104904175>

In [10]:
with tf.GradientTape() as tape:
    tape.watch(pi)
    result = tf.square(pi) # x^2 (x=3.14) , dx = 2*x (2x = 6.28)
gradient = tape.gradient(result, pi)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.28000020980835>

### Second Order Derivative

In [19]:
time = tf.Variable(0.)
time

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [20]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time**2  # c * x**2 (x=0), dx = 2cx (2cx = 0), dx^2 = 2c (2c = 9.8)
    speed = inner_tape.gradient(position, time)
    print(speed)
acceleration = outer_tape.gradient(speed, time)
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(9.8, shape=(), dtype=float32)


## Gradient of Rank 1 (Vector Calculus)

In [22]:
input_var = tf.Variable(initial_value=[1., 2., 3.])
input_var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [23]:
with tf.GradientTape() as tape:
    result = tf.square(input_var) # x^2, dx = 2*x
gradient = tape.gradient(result, input_var)
gradient

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>

In [35]:
time = tf.Variable([0., 1., 2., 3.])
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time**2  # c * x**2, dx = 2cx, dx^2 = 2c
    speed = inner_tape.gradient(position, time)
    print(speed)
acceleration = outer_tape.gradient(speed, time)
print(acceleration)

tf.Tensor([ 0.        9.8      19.6      29.400002], shape=(4,), dtype=float32)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([9.8, 9.8, 9.8, 9.8], dtype=float32)>

## Gradient of Rank 2+ (Tensor Calculus)

In [24]:
input_var = tf.Variable(initial_value=[[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
input_var

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [25]:
with tf.GradientTape() as tape:
    result = tf.square(input_var) # x^2, dx = 2*x
gradient = tape.gradient(result, input_var)
gradient

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]], dtype=float32)>

In [34]:
time = tf.Variable([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]])
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time**2  # c * x**2, dx = 2cx, dx^2 = 2c
    speed = inner_tape.gradient(position, time)
    print(speed)
acceleration = outer_tape.gradient(speed, time)
acceleration

tf.Tensor(
[[ 0.        9.8      19.6     ]
 [29.400002 39.2      49.      ]
 [58.800003 68.6      78.4     ]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8]], dtype=float32)>

end