In [1]:
import tensorflow as tf

### Constant Tensors

In [2]:
tf.ones(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [3]:
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [4]:
tf.constant([1, 2, 3], dtype="float32")

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [6]:
a = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")
# a[0][0] = 1 #Will throw error

### Random Tensors

In [7]:
tf.random.normal(shape=(3, 3), mean=0., stddev=1.)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.1198995 ,  0.7557336 ,  1.0287663 ],
       [-0.22923386, -0.30604476,  0.5125889 ],
       [-2.615722  , -0.4372871 , -0.39998338]], dtype=float32)>

In [8]:
tf.random.uniform(shape=(3, 3), minval=0., maxval=1.)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.71959674, 0.04029334, 0.20478392],
       [0.94624436, 0.12542725, 0.49320793],
       [0.04488337, 0.3402897 , 0.1954782 ]], dtype=float32)>

In [9]:
a = tf.random.normal(shape=(3, 3), mean=0., stddev=1.)
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.34757763,  0.613824  ,  1.0648501 ],
       [ 0.13543993,  0.03463688, -1.5027461 ],
       [ 0.49315548, -0.3353253 , -1.0665121 ]], dtype=float32)>

### Variable tensor

In [10]:
tf.Variable(initial_value=tf.random.normal(shape=(3, 3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-1.894359  ,  0.03101582,  0.06487634],
       [-0.70984143, -0.22419785,  0.39383   ],
       [ 0.13569185,  0.5285495 , -0.07704031]], dtype=float32)>

In [11]:
M = tf.Variable(initial_value=tf.random.normal(shape=(3, 3)))
M

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.10741875, -0.22521336, -1.257631  ],
       [ 0.79712003,  0.76800025, -0.61989135],
       [-0.8514341 ,  0.620181  , -0.51814735]], dtype=float32)>

In [12]:
# M[0][0] = 0
# Will throw error

In [13]:
# M[0, 0] = 0
# Will throw error

In [14]:
M[0, 0].assign(0) # Assign value
M

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.        , -0.22521336, -1.257631  ],
       [ 0.79712003,  0.76800025, -0.61989135],
       [-0.8514341 ,  0.620181  , -0.51814735]], dtype=float32)>

In [15]:
M[1, 1].assign(M[1, 1] + 100 ) # Add/Sub to element
M

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[  0.        ,  -0.22521336,  -1.257631  ],
       [  0.79712003, 100.768     ,  -0.61989135],
       [ -0.8514341 ,   0.620181  ,  -0.51814735]], dtype=float32)>

In [16]:
M.assign_add(tf.ones((3, 3)))
M

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[  1.        ,   0.77478665,  -0.25763094],
       [  1.7971201 , 101.768     ,   0.38010865],
       [  0.14856589,   1.6201811 ,   0.48185265]], dtype=float32)>

end