In [169]:
import numpy as np

### Rank 0

In [170]:
a = np.array(12)

In [171]:
a

array(12)

In [172]:
print(a)

12


In [173]:
a.view()

array(12)

In [174]:
a.ndim

0

In [175]:
a.shape

()

In [176]:
len(a.shape)

0

In [177]:
a.size

1

In [178]:
a.device # Always to CPU

'cpu'

In [179]:
a.itemsize

8

In [180]:
a.dtype

dtype('int64')

### Rank 1

In [181]:
b = np.array([1, 2, 3, 4, 5])

In [182]:
b

array([1, 2, 3, 4, 5])

In [183]:
print(b)

[1 2 3 4 5]


In [184]:
b.view()

array([1, 2, 3, 4, 5])

In [185]:
b.ndim

1

In [186]:
b.shape

(5,)

In [187]:
len(b.shape)

1

In [188]:
b.size

5

In [189]:
b.itemsize

8

In [190]:
b.dtype

dtype('int64')

In [191]:
b.T

array([1, 2, 3, 4, 5])

In [192]:
b.sum()

np.int64(15)

In [193]:
b.ravel()

array([1, 2, 3, 4, 5])

### Rank 2

In [194]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [195]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [197]:
c.view()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
c.ndim

2

In [199]:
c.shape

(3, 3)

In [200]:
len(c.shape)

2

In [201]:
c.size

9

In [202]:
c.dtype

dtype('int64')

In [203]:
c.trace()

np.int64(15)

In [204]:
c.diagonal()

array([1, 5, 9])

In [205]:
c.flatten() # Returns copy, Different arrays from original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
c.ravel() # Returns view, Reference array from original.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [208]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Rank 3

In [209]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]])

In [210]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [211]:
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [212]:
d.view()

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [213]:
d.ndim

3

In [214]:
d.shape

(3, 3, 3)

In [215]:
len(d.shape)

3

In [216]:
d.size

27

In [217]:
d.dtype

dtype('int64')

In [218]:
d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [219]:
d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [220]:
d.T

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 7, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 8, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 9, 19, 29]]])

end