In [76]:
import numpy as np

### Define

In [77]:
a = np.array(1)
a

array(1)

In [78]:
b = np.array(3.14)
b

array(3.14)

In [79]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
d = np.array([[-1, 2, -3], [4, -5, 6], [7, 8, -9]])
d

array([[-1,  2, -3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

### Element Wise Operation

In [81]:
c * b

array([[ 3.14,  6.28,  9.42],
       [12.56, 15.7 , 18.84],
       [21.98, 25.12, 28.26]])

In [82]:
c**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [83]:
c**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [84]:
sq = lambda x : abs(x)
sq(d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
relu = lambda x: np.maximum(0, x)
relu(d)

array([[0, 2, 0],
       [4, 0, 6],
       [7, 8, 0]])

In [86]:
np.maximum(0, d)

array([[0, 2, 0],
       [4, 0, 6],
       [7, 8, 0]])

In [87]:
c + d

array([[ 0,  4,  0],
       [ 8,  0, 12],
       [14, 16,  0]])

### Broadcasting

In [88]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
y = np.array([2, 1, 0])
y

array([2, 1, 0])

In [90]:
z = np.array([9, 6, 3, 0])
z

array([9, 6, 3, 0])

In [91]:
X + y

array([[ 3,  3,  3],
       [ 6,  6,  6],
       [ 9,  9,  9],
       [12, 12, 12]])

In [92]:
X + z

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [93]:
(X.T + z).T

array([[10, 11, 12],
       [10, 11, 12],
       [10, 11, 12],
       [10, 11, 12]])

### Tensor Product

In [94]:
c @ d

array([[ 28,  16, -18],
       [ 58,  31, -36],
       [ 88,  46, -54]])

In [95]:
np.matmul(c, d)

array([[ 28,  16, -18],
       [ 58,  31, -36],
       [ 88,  46, -54]])

In [96]:
np.dot(c, d)

array([[ 28,  16, -18],
       [ 58,  31, -36],
       [ 88,  46, -54]])

### Tensor Reshaping

In [97]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
M.shape

(3, 4)

In [99]:
M.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [100]:
M.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [101]:
M.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
M.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
M.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [104]:
M.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

end