In [8]:
import tensorflow as tf

### Tensors

In [9]:
tf.ones(shape=(4, 3)) # np.ones(shape=(4, 3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
tf.zeros(shape=(3, 4)) # np.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [11]:
tf.constant([1, 2, 3], dtype="float32") # np.array([1, 2, 3], dtype="float32")

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [12]:
x = tf.random.normal(shape=(3, 3), mean=0., stddev=1.) #np.random.normal(size=(3, 3), loc=0., scale=1.).
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.4392473e-01,  1.3672718e-01,  1.3229171e+00],
       [ 1.5943304e-03, -8.0044025e-01, -1.7398348e+00],
       [-6.7747378e-01,  5.5960160e-01,  9.1448677e-01]], dtype=float32)>

In [13]:
x = tf.random.uniform(shape=(3, 3), minval=0., maxval=1.) # random.uniform(size=(3, 3), low=0., high=1.)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7465702 , 0.98463404, 0.88718486],
       [0.05589581, 0.4237026 , 0.1366216 ],
       [0.7390847 , 0.08865798, 0.387712  ]], dtype=float32)>

In [14]:
x = tf.ones(shape=(2, 2))
x[0, 0] = 0.0   # Immutability. Tensors are immutable by default

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [15]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 3))) # Mutable tensor AKA TF variable
v

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.73148376,  1.0887533 , -1.5233706 ],
       [-0.9966424 , -0.16170354,  0.643206  ],
       [ 0.43954116, -1.0068201 ,  0.33967444]], dtype=float32)>

In [16]:
v[0, 0] = 0 # But not like this
v

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
v[0, 0].assign(0) # Like this
v
# assign_add (+=), assign_sub (-=)

### Tensor Operation

In [ ]:
a = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")
a

In [ ]:
b = tf.square(a)
b

In [17]:
c = tf.sqrt(a)
c

NameError: name 'a' is not defined

In [ ]:
d = b + c
d

In [ ]:
e = tf.matmul(a, b)
e

In [ ]:
f = tf.concat((a, b), axis=0)
f

In [ ]:
g = tf.concat((a, b), axis=1)
g

In [ ]:
input_var = tf.Variable(initial_value=3.0)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
result, gradient

In [ ]:
input_var = tf.Variable(initial_value=3.0)
input_var

In [ ]:
with tf.GradientTape() as tape:
    res1 = input_var*2
    res2 = res1**3
    res3 = res2**0.5
    result = res3
gradient = tape.gradient(result, input_var)
result, gradient

In [18]:
input_const = tf.constant(3.0)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
result, gradient

(<tf.Tensor: shape=(), dtype=float32, numpy=9.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [19]:
time = tf.Variable(0.11)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time**2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
time, position, speed, acceleration

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.10999999940395355>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.059289999306201935>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0780000686645508>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.800000190734863>)

In [20]:
@tf.function  # Compiling function to make it run faster - graph mode (Faster)
def denseA(inputs, W, b):
    return tf.nn.relu(tf.matmul(inputs, W) + b)



In [21]:
@tf.function(jit_compile=True) #  # Compiling function to make it run faster - XLA mode (Very fast)
def denseB(inputs, W, b):
    return tf.nn.relu(tf.matmul(inputs, W) + b)



In [22]:
input_size=10000
output_size=10000

W = tf.keras.Variable(shape=(input_size, output_size), initializer="uniform")
b = tf.keras.Variable(shape=(output_size,), initializer="uniform")
inputs = tf.keras.Variable(shape=(input_size, input_size), initializer="uniform")
W.shape, b.shape, inputs.shape


(TensorShape([10000, 10000]),
 TensorShape([10000]),
 TensorShape([10000, 10000]))

In [23]:
import time

start1 = time.time()
res1 = denseA(inputs, W, b)
end1 = time.time()
end1 - start1

5.7646260261535645

In [24]:
start2 = time.time()
res2 = denseB(inputs, W, b)
end2 = time.time()
end2 - start2

9.082935810089111