In [2]:
import jax
from jax import numpy as jnp

### Tensors

In [3]:
jnp.ones(shape=(3, 3))

Array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [4]:
jnp.zeros(shape=(3, 4))

Array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [5]:
jnp.array([1, 2, 3], dtype="float32")

Array([1., 2., 3.], dtype=float32)

In [6]:
jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")

Array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [7]:
seed_key = jax.random.key(123)
seed_key

Array((), dtype=key<fry>) overlaying:
[  0 123]

In [8]:
jax.random.normal(seed_key, shape=(3,))

Array([1.6359469 , 0.8408094 , 0.02212393], dtype=float32)

In [9]:
new_seed_key = jax.random.split(seed_key, num=1)[0]
new_seed_key


Array((), dtype=key<fry>) overlaying:
[ 969380169 3408994049]

In [10]:
jax.random.normal(new_seed_key, shape=(3,))

Array([-0.49093357, -0.9478693 , -1.775197  ], dtype=float32)

In [11]:
seed_key_a = jax.random.key(42)
print("Seed Key A :", seed_key_a)
for i in range(10):
    seed_key_a = jax.random.split(seed_key_a, num=1)[0]
    print(f"New Seed Key A {i} :", seed_key_a)

Seed Key A : Array((), dtype=key<fry>) overlaying:
[ 0 42]
New Seed Key A 0 : Array((), dtype=key<fry>) overlaying:
[1832780943  270669613]
New Seed Key A 1 : Array((), dtype=key<fry>) overlaying:
[1012194634 3152801799]
New Seed Key A 2 : Array((), dtype=key<fry>) overlaying:
[1773327481 1441649378]
New Seed Key A 3 : Array((), dtype=key<fry>) overlaying:
[2852371275 1535037118]
New Seed Key A 4 : Array((), dtype=key<fry>) overlaying:
[ 827075891 2691092366]
New Seed Key A 5 : Array((), dtype=key<fry>) overlaying:
[ 111275749 2795491959]
New Seed Key A 6 : Array((), dtype=key<fry>) overlaying:
[4277279094 3231914188]
New Seed Key A 7 : Array((), dtype=key<fry>) overlaying:
[3895678382 3429534896]
New Seed Key A 8 : Array((), dtype=key<fry>) overlaying:
[144179800 435181257]
New Seed Key A 9 : Array((), dtype=key<fry>) overlaying:
[1825841970 3512247751]


In [12]:
x = jnp.array([1, 2, 3], dtype="float32")
x

Array([1., 2., 3.], dtype=float32)

In [13]:
x[0] = 10 # Immutable

TypeError: JAX arrays are immutable and do not support in-place item assignment. Instead of x[idx] = y, use x = x.at[idx].set(y) or another .at[] method: https://docs.jax.dev/en/latest/_autosummary/jax.numpy.ndarray.at.html

In [14]:
x = x.at[0].set(10) # Workaround
x

Array([10.,  2.,  3.], dtype=float32)

In [15]:
a = jnp.ones((2, 2))
a

Array([[1., 1.],
       [1., 1.]], dtype=float32)

In [16]:
b = jnp.square(a)
b

Array([[1., 1.],
       [1., 1.]], dtype=float32)

In [17]:
c = jnp.sqrt(a)
c

Array([[1., 1.],
       [1., 1.]], dtype=float32)

In [18]:
d = b + c
d

Array([[2., 2.],
       [2., 2.]], dtype=float32)

In [19]:
e = jnp.matmul(a, b)
e

Array([[2., 2.],
       [2., 2.]], dtype=float32)

In [20]:
e *= d
e

Array([[4., 4.],
       [4., 4.]], dtype=float32)

In [21]:
def dense(inputs, W, b):
    return jax.nn.relu(jnp.matmul(inputs, W) + b)

In [22]:
def functionA(input_var):
    return jnp.square(input_var)

In [23]:
grad_functionA = jax.grad(functionA)
grad_functionA

<function __main__.functionA(input_var)>

In [24]:
input_var = jnp.array(3.0)
input_var

Array(3., dtype=float32, weak_type=True)

In [25]:
functionA(input_var)

Array(9., dtype=float32, weak_type=True)

In [26]:
grad_functionA(input_var)

Array(6., dtype=float32, weak_type=True)

In [27]:
grad_functionA = jax.value_and_grad(functionA)
grad_functionA(input_var)

(Array(9., dtype=float32, weak_type=True),
 Array(6., dtype=float32, weak_type=True))