In [1]:
import torch

### Tensors

In [2]:
torch.ones(size=(3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
torch.zeros(size=(4, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [5]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [6]:
torch.normal(mean=torch.zeros(size=(3, 3)), std=torch.ones(size=(3, 3)))

tensor([[-0.3822,  0.5282,  0.2116],
        [ 0.7663, -0.5900,  0.4974],
        [-0.1568, -0.3615, -0.2214]])

In [7]:
torch.rand(3, 3)

tensor([[0.0616, 0.0817, 0.0467],
        [0.0800, 0.6399, 0.9465],
        [0.9121, 0.3018, 0.3410]])

In [8]:
x = torch.zeros(size=(3, 3))
x[1, 1] = 1 # Its mutable
x

tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])

In [9]:
# Torch Parameter
x = torch.zeros(size=(3, 3))
p = torch.nn.parameter.Parameter(data=x)
p

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)

In [10]:
type(p)

torch.nn.parameter.Parameter

### Tensor Operation

In [11]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
b = torch.square(a)
b

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [13]:
c = torch.sqrt(a)
c

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])

In [14]:
d = b + c
d

tensor([[ 2.0000,  5.4142, 10.7321],
        [18.0000, 27.2361, 38.4495],
        [51.6458, 66.8284, 84.0000]])

In [15]:
e = torch.matmul(a, b)
e

tensor([[ 180.,  246.,  324.],
        [ 378.,  525.,  702.],
        [ 576.,  804., 1080.]])

In [16]:
f = torch.cat((a, b), dim=0)
f

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [17]:
g = torch.cat((a, b), dim=1)
g

tensor([[ 1.,  2.,  3.,  1.,  4.,  9.],
        [ 4.,  5.,  6., 16., 25., 36.],
        [ 7.,  8.,  9., 49., 64., 81.]])

In [18]:
def dense(inputs, W, b):
    return torch.nn.relu(torch.matmul(inputs, W) + b)

In [19]:
input_var = torch.tensor(3.0, requires_grad=True)
input_var

tensor(3., requires_grad=True)

In [20]:
result = torch.square(input_var)
result

tensor(9., grad_fn=<PowBackward0>)

In [21]:
result.backward()

In [22]:
gradient = input_var.grad
gradient

tensor(6.)

In [23]:
input_var.grad = None

In [24]:
import torch
time = torch.tensor(0.11, requires_grad=True)
position = 4.9 * time**2
position.backward(create_graph=True)
speed = time.grad
time.grad = None
speed.backward()
acceleration = time.grad
print(f"Time:         {time.item():.4f}")
print(f"Position:     {position.item():.4f}")
print(f"Speed:        {speed.item():.4f}")
print(f"Acceleration: {acceleration.item():.4f}")

Time:         0.1100
Position:     0.0593
Speed:        1.0780
Acceleration: 9.8000


C:\Users\PRASHANTH N\PycharmProjects\MTechSem2\gpu\.venv\Lib\site-packages\torch\autograd\graph.py:825: UserWarning: Using backward() with create_graph=True will create a reference cycle between the parameter and its gradient which can cause a memory leak. We recommend using autograd.grad when creating the graph to avoid this. If you have to use this function, make sure to reset the .grad fields of your parameters to None after use to break the cycle and avoid the leak. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\autograd\engine.cpp:1206.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


In [25]:
import torch

time = torch.tensor(0.11, requires_grad=True)
position = 4.9 * time**2
speed = torch.autograd.grad(outputs=position, inputs=time, create_graph=True)[0]
acceleration = torch.autograd.grad(outputs=speed, inputs=time)[0]
print(f"Time:         {time.item():.4f}")
print(f"Position:     {position.item():.4f}")
print(f"Speed:        {speed.item():.4f}")
print(f"Acceleration: {acceleration.item():.4f}")

Time:         0.1100
Position:     0.0593
Speed:        1.0780
Acceleration: 9.8000
