In [1]:
import jax
from jax import numpy as jnp

## Gradient of Rank 0 (Calculus)

### First Order Derivative

In [3]:
input_var = jnp.array(3.0)
input_var

Array(3., dtype=float32, weak_type=True)

In [7]:
fun = lambda x : jnp.square(x) # x^2 (x=3) , dx = 2*x (2x = 6)
grad_fun = jax.grad(fun)
value = fun(input_var)
gradient = grad_fun(input_var)
print(value)
print(gradient)

9.0
6.0


In [12]:
pi = jnp.array(3.14)
fun = lambda x : jnp.square(x)# x^2 (x=3.14) , dx = 2*x (2x = 6.28)
grad_fun = jax.value_and_grad(fun)
value, gradient = grad_fun(pi)
print(value)
print(gradient)

9.859601
6.28


### Second Order Derivative

In [14]:
time = jnp.array(0.)
time

Array(0., dtype=float32, weak_type=True)

In [16]:
position_fun = lambda time: 4.9 * time**2  # c * x**2 (x=0), dx = 2cx (2cx = 0), dx^2 = 2c (2c = 9.8)
speed_fun = jax.grad(position_fun)
acceleration_fun = jax.grad(speed_fun)
speed = speed_fun(time)
acceleration = acceleration_fun(time)
print(speed)
print(acceleration)

0.0
9.8


## Gradient of Rank 1 (Vector Calculus)

In [17]:
input_var = jnp.array([1., 2., 3.])
input_var

Array([1., 2., 3.], dtype=float32)

In [22]:
result_fn = lambda x: jnp.square(x).sum() # x^2, dx = 2*x
gradient_fn = jax.grad(result_fn)
gradient = gradient_fn(input_var)
gradient

Array([2., 4., 6.], dtype=float32)

In [33]:
time = jnp.array([0., 1., 2., 3.])
position_fn = lambda time: (4.9 * time**2).sum()  # c * x**2, dx = 2cx, dx^2 = 2c
speed_fn = jax.grad(position_fn)
speed_fn1 = lambda x : sum(speed_fn(x))
acceleration_fn = jax.grad(speed_fn1)
speed = speed_fn(time)
acceleration = acceleration_fn(time)
print(speed)
print(acceleration)

[ 0.        9.8      19.6      29.400002]
[9.8 9.8 9.8 9.8]


## Gradient of Rank 2+ (Tensor Calculus)

In [34]:
input_var = jnp.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
input_var

Array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [37]:
result_fn = lambda x : jnp.square(x).sum() # x^2, dx = 2*x
gradient_fn = jax.grad(result_fn)
gradient = gradient_fn(input_var)
gradient

Array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]], dtype=float32)

In [41]:
time = jnp.array([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]])
position_fn = lambda time : (4.9 * time**2).sum()  # c * x**2, dx = 2cx, dx^2 = 2c
speed_fn = jax.grad(position_fn)
speed_fn1 = lambda x : sum(sum(speed_fn(x)))
acceleration_fn = jax.grad(speed_fn1)
speed = speed_fn(time)
acceleration = acceleration_fn(time)
print(speed)
acceleration

[[ 0.        9.8      19.6     ]
 [29.400002 39.2      49.      ]
 [58.800003 68.6      78.4     ]]


Array([[9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8]], dtype=float32)

end