In [1]:
import jax
from jax import numpy as jnp

### Define

In [3]:
a = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")
a

Array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [4]:
b = jnp.array([[-1, 2, -3], [4, -5, 6], [7, -8, -9]], dtype="float32")
b

Array([[-1.,  2., -3.],
       [ 4., -5.,  6.],
       [ 7., -8., -9.]], dtype=float32)

### Operations

In [5]:
b ** 2

Array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [6]:
b * 2

Array([[ -2.,   4.,  -6.],
       [  8., -10.,  12.],
       [ 14., -16., -18.]], dtype=float32)

In [7]:
b + 10

Array([[ 9., 12.,  7.],
       [14.,  5., 16.],
       [17.,  2.,  1.]], dtype=float32)

In [8]:
a + b

Array([[ 0.,  4.,  0.],
       [ 8.,  0., 12.],
       [14.,  0.,  0.]], dtype=float32)

In [9]:
a @ b

Array([[ 28., -32., -18.],
       [ 58., -65., -36.],
       [ 88., -98., -54.]], dtype=float32)

In [11]:
jnp.matmul(a, b)

Array([[ 28., -32., -18.],
       [ 58., -65., -36.],
       [ 88., -98., -54.]], dtype=float32)

In [14]:
jnp.concat((a, b), axis=0)

Array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [-1.,  2., -3.],
       [ 4., -5.,  6.],
       [ 7., -8., -9.]], dtype=float32)

In [15]:
jnp.concat((a, b), axis=1)

Array([[ 1.,  2.,  3., -1.,  2., -3.],
       [ 4.,  5.,  6.,  4., -5.,  6.],
       [ 7.,  8.,  9.,  7., -8., -9.]], dtype=float32)

end