In [28]:
from jax import numpy as jnp
import jax

### Constant Tensors

In [29]:
jnp.ones(shape=(3, 3))

Array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [30]:
jnp.zeros(shape=(3, 3))

Array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [31]:
jnp.array([1, 2, 3], dtype="float32")

Array([1., 2., 3.], dtype=float32)

In [32]:
jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")

Array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [33]:
a = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")
#a[0][0] = 100 # Throws error

### Random Tensors

In [34]:
seed = jax.random.key(42)
seed

Array((), dtype=key<fry>) overlaying:
[ 0 42]

In [35]:
jax.random.normal(key=seed, shape=(3, 3))

Array([[-0.02830462,  0.46713185,  0.29570296],
       [ 0.15354592, -0.12403282,  0.21692315],
       [-1.440879  ,  0.7558599 ,  0.52140963]], dtype=float32)

In [36]:
jax.random.uniform(key=seed, shape=(3, 3))

Array([[0.48870957, 0.6797972 , 0.6162715 ],
       [0.5610161 , 0.4506446 , 0.58586586],
       [0.07480943, 0.7751334 , 0.69895923]], dtype=float32)

### tensor Assigment

In [37]:
a = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype="float32")
a

Array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [38]:
a.at[1, 1].set(100) # Returns new array

Array([[  1.,   2.,   3.],
       [  4., 100.,   6.],
       [  7.,   8.,   9.]], dtype=float32)

end