In [2]:
import torch

### Define

In [11]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
b = torch.tensor([[-1, 2, -3], [4, -5, 6], [7, -8, -9]], dtype=torch.float32)
b

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.],
        [ 7., -8., -9.]])

### Operations

In [13]:
b ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [14]:
b * 2

tensor([[ -2.,   4.,  -6.],
        [  8., -10.,  12.],
        [ 14., -16., -18.]])

In [15]:
b + 10

tensor([[ 9., 12.,  7.],
        [14.,  5., 16.],
        [17.,  2.,  1.]])

In [17]:
a + b

tensor([[ 0.,  4.,  0.],
        [ 8.,  0., 12.],
        [14.,  0.,  0.]])

In [18]:
a @ b

tensor([[ 28., -32., -18.],
        [ 58., -65., -36.],
        [ 88., -98., -54.]])

In [19]:
torch.matmul(a, b)

tensor([[ 28., -32., -18.],
        [ 58., -65., -36.],
        [ 88., -98., -54.]])

In [20]:
torch.concat((a, b), dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [-1.,  2., -3.],
        [ 4., -5.,  6.],
        [ 7., -8., -9.]])

In [21]:
torch.concat((a, b), dim=1)

tensor([[ 1.,  2.,  3., -1.,  2., -3.],
        [ 4.,  5.,  6.,  4., -5.,  6.],
        [ 7.,  8.,  9.,  7., -8., -9.]])

end