In [11]:
import torch

### Constant Tensors

In [12]:
torch.ones(size=(3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.zeros(size=(3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [15]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [16]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
a[0][0] = 100
a

tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]])

### Random Tensors

In [17]:
torch.normal(mean=torch.zeros(size=(3, 3)), std=torch.ones(size=(3, 3)))

tensor([[-1.5554, -1.6994,  0.6735],
        [-0.8942,  1.0009, -1.0903],
        [ 1.1789, -0.8854, -0.8468]])

In [18]:
torch.rand(3, 3)

tensor([[0.9285, 0.0484, 0.4427],
        [0.3611, 0.7491, 0.1575],
        [0.6362, 0.2764, 0.9891]])

### Parameter tensor

In [19]:
x = torch.ones(size=(3, 3))
p = torch.nn.parameter.Parameter(data=x)
p

Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

end