In [79]:
import torch

## Gradient of Rank 0 (Calculus)

### First Order Derivative

In [80]:
input_var = torch.tensor(data=3.0, requires_grad=True)
input_var

tensor(3., requires_grad=True)

In [81]:
result = torch.square(input_var) # x^2 (x=3) , dx = 2*x (2x = 6)
result.backward()
gradient = input_var.grad
input_var.grad = None
gradient

tensor(6.)

In [82]:
pi = torch.tensor(3.14, requires_grad=True)
result = torch.square(pi) # x^2 (x=3.14) , dx = 2*x (2x = 6.28)
result.backward()
gradient = pi.grad
pi.grad = None
gradient

tensor(6.2800)

### Second Order Derivative

In [83]:
time = torch.tensor(0., requires_grad=True)
time

tensor(0., requires_grad=True)

In [84]:
position = 4.9 * time**2  # c * x**2 (x=0), dx = 2cx (2cx = 0), dx^2 = 2c (2c = 9.8)
position.backward(create_graph=True)
speed = time.grad
time.grad = None
speed.backward()
acceleration = time.grad
time.grad = None
print(speed)
print(acceleration)

tensor(0., grad_fn=<CopyBackwards>)
tensor(9.8000)


## Gradient of Rank 1 (Vector Calculus)

In [85]:
input_var = torch.tensor(data=[1., 2., 3.], requires_grad=True)
input_var

tensor([1., 2., 3.], requires_grad=True)

In [86]:
result = torch.square(input_var) # x^2, dx = 2*x
result.sum().backward()
gradient = input_var.grad
input_var.grad = None
gradient

tensor([2., 4., 6.])

In [87]:
time = torch.tensor([0., 1., 2., 3.], requires_grad=True)
position = 4.9 * time**2  # c * x**2, dx = 2cx, dx^2 = 2c
position.sum().backward(create_graph=True)
speed = time.grad
time.grad = None
speed.sum().backward()
acceleration = time.grad
time.grad = None
print(speed)
print(acceleration)

tensor([ 0.0000,  9.8000, 19.6000, 29.4000], grad_fn=<CopyBackwards>)
tensor([9.8000, 9.8000, 9.8000, 9.8000])


## Gradient of Rank 2+ (Tensor Calculus)

In [88]:
input_var = torch.tensor(data=[[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], requires_grad=True)
input_var

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [89]:
result = torch.square(input_var) # x^2, dx = 2*x
result.sum().backward()
gradient = input_var.grad
input_var.grad = None
gradient

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

In [90]:
time = torch.tensor([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]], requires_grad=True)
position = 4.9 * time**2  # c * x**2, dx = 2cx, dx^2 = 2c
position.sum().backward(create_graph=True)
speed = time.grad
time.grad = None
speed.sum().backward()
acceleration = time.grad
time.grad = None
print(speed)
acceleration

tensor([[ 0.0000,  9.8000, 19.6000],
        [29.4000, 39.2000, 49.0000],
        [58.8000, 68.6000, 78.4000]], grad_fn=<CopyBackwards>)


tensor([[9.8000, 9.8000, 9.8000],
        [9.8000, 9.8000, 9.8000],
        [9.8000, 9.8000, 9.8000]])

end