In [4]:
import numpy as np

In [5]:
def step_function(z, threshold=0):
    return (z >= threshold).astype(int)

In [6]:
def initialize_weights(n_inputs, n_outputs):
    weights = np.random.randn(n_outputs, n_inputs)
    bias = np.random.randn(n_outputs)
    return weights, bias

In [50]:
def forward(X, weights, bias):
    z = X @ weights.T + bias
    y_pred = step_function(z)
    return y_pred

In [94]:
def score(X, y, weights, bias):
    predictions = predict(X, weights, bias)
    y = y.reshape(-1, predictions.shape[1])
    return np.mean(predictions == y)

In [95]:
def predict(X, weights, biases):
    z = X @ weights.T + biases
    return step_function(z)

In [138]:
def train(X, y, epochs=100, learning_rate=1):
    n_inputs = X.shape[1]
    n_outputs = y.shape[1] if len(y.shape) == 2 else 1
    weights, bias = initialize_weights(n_inputs, n_outputs)
    for epoch in range(epochs):
        for x, target in zip(X, y):
            prediction = forward(x.reshape(1, -1), weights, bias)[0]
            error = target - prediction
            weights += (learning_rate * np.outer(error, x))
            bias += learning_rate * error
    return weights, bias

In [139]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) # AND
y = np.array([0, 0, 0, 1])

weights, bias = train(X, y, epochs=10)

print("\nWeights:", weights)
print("Bias:", bias)

print("\nPredictions:")
print(predict(X, weights, bias))

print("\nAccuracy:", score(X, y, weights, bias))


Weights: [[1.84686322 1.27374229]]
Bias: [-2.50992195]

Predictions:
[[0]
 [0]
 [0]
 [1]]

Accuracy: 1.0


In [99]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) # Flips
y = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])

weights, bias = train(X, y, epochs=10)

print("\nWeights:", weights)
print("Bias:", bias)

print("\nPredictions:")
print(predict(X, weights, bias))

print("\nAccuracy:", score(X, y, weights, bias))


Weights: [[-2.11746872  0.26506702]
 [ 0.2126688  -0.84201833]]
Bias: [0.52432306 0.07567088]

Predictions:
[[1 1]
 [1 0]
 [0 1]
 [0 0]]

Accuracy: 1.0


In [113]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) # OR
y = np.array([0, 1, 1, 1])

weights, bias = train(X, y, epochs=5)

print("\nWeights:", weights)
print("Bias:", bias)

print("\nPredictions:")
print(predict(X, weights, bias))

print("\nAccuracy:", score(X, y, weights, bias))


Weights: [[0.88728307 1.35795886]]
Bias: [-0.49824198]

Predictions:
[[0]
 [1]
 [1]
 [1]]

Accuracy: 1.0
