Single Neuron / Linear Threshold Unit (LTU) / Threshold Logical Unit (TLU)

### Load Data

In [118]:
inputs_and = [[0, 0], [0, 1], [1, 1]] # AND Operation
outputs_and = [0, 0, 1]

inputs_and_test = [[1, 0], [1, 1]]

In [119]:
inputs_vote = [[0, 0, 0], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 1]] # Voting Operation
outputs_vote = [0, 0, 1, 0, 1, 1]

inputs_vote_test = [[1, 1, 0], [0, 0, 1]]

### My Code

In [120]:
import random

In [121]:
def linear_function(inputs, weights, bias):
    linear_combo = 0
    for inp, weight in zip(inputs, weights):
        linear_combo += inp * weight
    return linear_combo + bias

In [122]:
def step_function(z, thresh=0): # lift Function, Activation Function, etc
    # Heaviside step function
    if z < thresh:
        return 0
    #if z >= thresh:
    else:
        return 1

In [123]:
def TLU(inputs, weights, bias, thresh): # Neuron
    linear_result = linear_function(inputs, weights, bias)
    neuron_result = step_function(linear_result, thresh)
    return neuron_result

In [124]:
def init_weights(no_of_neurons=1, input_shape=1):
    weights = []
    bias = []
    for i in range(no_of_neurons):
        weight = [1]*input_shape
        weights.append(weight)
        bias.append(random.random())
    return weights, bias

In [125]:
def learning_rule(weight, bias, X, y, y_pred, lr=0.0001):
    for i in range(len(X)):
        weight[i] = weight[i] + lr * X[i] * (y-y_pred)
    bias = bias + lr*(y-y_pred)
    return weight, bias

In [126]:
def perceptron(X, y, no_of_neurons=1, no_epochs = 1, thresh=0): # FC layer / Dense Layer
    weights, bias = init_weights(no_of_neurons, len(X[0]))
    for epoch in range(no_epochs):
        for instance_idx in range(len(X)):
            for j in range(no_of_neurons):
                y_pred = TLU(X[instance_idx], weights[j], bias[j], thresh)
                weights[j], bias[j] = learning_rule(weights[j], bias[j], X[instance_idx], y[instance_idx], y_pred)
    return weights, bias

In [127]:
def predict(inputs, weights, bias, thresh=0):
    outputs = []
    for inp in inputs:
        for weight, b in zip(weights, bias):
            y_pred = TLU(inp, weight, b, thresh)
            outputs.append(y_pred)
    return outputs

In [128]:
weights, bias = perceptron(inputs_and, outputs_and, 1, 1, 2)
predict(inputs_and_test, weights, bias, thresh=2)

[0, 1]

In [129]:
weights, bias = perceptron(inputs_vote, outputs_vote, 1, 1, 2)
predict(inputs_vote_test, weights, bias, thresh=2)

[1, 0]

### Using Numpy

In [130]:
import numpy as np

In [131]:
def linear_function(inputs, weights, bias):
    return inputs @ weights.T + bias

In [132]:
def step_function(z, thresh=0): # lift Function, Activation Function, etc
    # Heaviside step function
    a = z>=thresh
    return a.astype("int")

In [133]:
def TLU(inputs, weights, bias, thresh): # Neuron
    linear_result = linear_function(inputs, weights, bias)
    neuron_result = step_function(linear_result, thresh)
    return neuron_result.flatten()

In [134]:
def init_weights(no_of_neurons=1, input_shape=1):
    weights = np.ones((no_of_neurons, input_shape))
    bias = np.random.random(no_of_neurons)
    return weights, bias

In [135]:
def learning_rule(weight, bias, X, y, y_pred, lr=0.0001):
    weight = weight + lr * (X.T @ (y-y_pred))
    bias = bias + lr*(y-y_pred)[0]
    return weight, bias

In [136]:
def perceptron(X, y, no_of_neurons=1, no_epochs = 1, thresh=0): # FC layer / Dense Layer
    weights, bias = init_weights(no_of_neurons, len(X[0]))
    for epoch in range(no_epochs):
        y_pred = TLU(X, weights, bias, thresh)
        weights, bias = learning_rule(weights, bias, X, y, y_pred)
    return weights, bias

In [137]:
def predict(inputs, weights, bias, thresh=0):
    return TLU(inputs, weights, bias, thresh)

In [138]:
weights, bias = perceptron(np.array(inputs_and), np.array(outputs_and), 1, 1, 2)
predict(np.array(inputs_and_test), weights, bias, thresh=2)

array([0, 1])

In [139]:
weights, bias = perceptron(np.array(inputs_vote), np.array(outputs_vote), 1, 1, 2)
predict(np.array(inputs_vote_test), weights, bias, thresh=2)

array([1, 0])

### Using Sklearn

In [140]:
from sklearn.linear_model import Perceptron

In [141]:
per_clf = Perceptron(random_state=42)
per_clf.fit(inputs_and, outputs_and)
per_clf.predict(inputs_and_test)

array([1, 1])

In [142]:
per_clf = Perceptron(random_state=42)
per_clf.fit(inputs_vote, outputs_vote)
per_clf.predict(inputs_vote_test)

array([0, 1])