In [6]:
import torch.nn as nn
import torch

### Model

In [31]:
model = nn.Linear(2, 2)
x = torch.tensor([[10., 20.]])
y = torch.tensor([[0., 1.]])

In [32]:
output = model(x)
loss = nn.functional.mse_loss(output, y)
loss.backward()

In [33]:
print("Before clipping:")
print(model.weight.grad)
print(model.bias.grad)

Before clipping:
tensor([[  60.3915,  120.7830],
        [ -71.4061, -142.8121]])
tensor([ 6.0392, -7.1406])


### Clip Grad Norm

In [34]:
norm = nn.utils.clip_grad_norm_(model.parameters(), max_norm=1)

In [35]:
print("\nOriginal total gradient norm:", norm)


Original total gradient norm: tensor(209.3258)


In [36]:
print("\nAfter clipping:")
print(model.weight.grad)
print(model.bias.grad)


After clipping:
tensor([[ 0.2885,  0.5770],
        [-0.3411, -0.6822]])
tensor([ 0.0289, -0.0341])


In [13]:
### Clip Grad Value

In [19]:
val = nn.utils.clip_grad_value_(model.parameters(), clip_value=50)

In [20]:
print("\nAfter clipping:")
print(model.weight.grad)
print(model.bias.grad)


After clipping:
tensor([[50.0000, 50.0000],
        [48.5501, 50.0000]])
tensor([9.1407, 4.8550])


end